version: '3.2'
services:
  es1:
    image: lgslm/elasticsearch:v1.0.0
    environment:
      - discovery.seed_host=es2:9300
      - node.name=es1
      - cluster.name=es-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_volume:/usr/share/elasticsearch/data      
    networks:
      - kafka-clients-net

  es2:
    image: lgslm/elasticsearch:v1.0.0
    environment:
      - discovery.seed_host=es1:9300
      - node.name=es2
      - cluster.name=es-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    volumes:
      - es_volume:/usr/share/elasticsearch/data
    networks:
      - kafka-clients-net

volumes:
  es_volume:

networks:
  kafka-clients-net:
    external: true
